name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ALCHEMY_API: ${{ secrets.ALCHEMY_API }}
      __DANGEROUS_OVM_IGNORE_ERRORS__: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint

  test:
    runs-on: ubuntu-latest
    env:
      ALCHEMY_API: ${{ secrets.ALCHEMY_API }}
      __DANGEROUS_OVM_IGNORE_ERRORS__: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  slither:
    runs-on: ubuntu-latest
    env:
      ALCHEMY_API: ${{ secrets.ALCHEMY_API }}
      __DANGEROUS_OVM_IGNORE_ERRORS__: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python -m pip install --upgrade pip
    - run: pip3 install slither-analyzer
    - run: slither . --exclude-informational --exclude-low --exclude-medium --exclude-optimization
